[package]

name = "bio"
version = "0.3.5"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]
description = "A rusty bioinformatics library. This library provides implementations of many algorithms and data structures that are useful for bioinformatics."
homepage = "https://github.com/johanneskoester/rust-bio"
readme = "README.md"
license = "MIT"

[dependencies]
csv = "*"
rustc-serialize = "*"
num = "*"
itertools = "*"
