[package]

name = "bio"
version = "0.0.1"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]
description = "A rusty bioinformatics library. This library will provide various algorithms and functions useful for bioinformatics applications. Currently, it is focused towards NGS, and content is added as needed."
homepage = "https://rust-bio.readthedocs.org"
readme = "README.md"
license = "MIT"

[dependencies]

log= "0.1.9"
